export { apiRequest } from './client';
export type { RequestOptions } from './client';
export { ApiError, describeError } from './errors';
export type { ApiErrorKind } from './errors';
export {
  fetchMe,
  login,
  verifyTwoFactor,
  logout,
  logoutAll,
  pairInit,
  pairCancel,
  pairClaim,
  pairStatus,
  fetchDashboard,
  fetchDashboardSparkline,
  fetchFortuneDashboard,
  fetchFortuneReadings,
  fetchFortuneReadingsStats,
  fetchFortuneReading,
  fetchWallets,
  fetchWalletsSystemStats,
  fetchWalletTransactions,
  fetchWallet,
  adjustWalletBalance,
  lockWallet,
  unlockWallet,
  suspendWallet,
  unsuspendWallet,
  fetchWithdrawals,
  fetchPendingWithdrawals,
  fetchWithdrawal,
  approveWithdrawal,
  rejectWithdrawal,
  completeWithdrawal,
  batchApproveWithdrawals,
  fetchAiDashboard,
  fetchAiTimeseries,
  fetchAiProviders,
  fetchAiProvider,
  toggleAiProvider,
  testAiProvider,
  fetchAiBots,
  fetchAiBot,
  toggleAiBot,
  testAiBot,
  fetchUsers,
  fetchUserStats,
  fetchUser,
  fetchAnalyticsOverview,
  fetchRanks,
  fetchMarketplaceDashboard,
  fetchMarketplaceOrders,
  fetchUserReadings,
  fetchAdminsOnline,
  markReadingPaid,
  refundReading,
  cancelReading,
  sendChatMessage,
  suggestChatReply,
  eveChat,
  fetchSmsInbox,
  fetchPaymentReconStats,
  matchSms,
  rejectSms,
  fetchModerationSuspects,
  fetchModerationBanned,
  banUser,
  unbanUser,
  fetchModerationRules,
  updateModerationRules,
  fetchPlaygroundProviders,
  runPlayground,
  fetchPerProviderUsage,
  fetchFortuneWorkersQueue,
} from './endpoints';
export type {
  AdminMe,
  LoginPayload,
  LoginResponse,
  AdminPresence,
  SmsInboxItem,
  ModerationSuspect,
  ModerationBan,
  PlaygroundProvider,
  PlaygroundResult,
  EveChatRequest,
  EveChatResponse,
  ProviderUsageRow,
  FortuneWorkersQueue,
  FortuneInFlightRow,
  FortuneCompletedRow,
} from './endpoints';
export type {
  DashboardResponse,
  DashboardHero,
  DashboardStats,
  DashboardSparkPoint,
  DashboardQuickActions,
  FortuneReading,
  FortuneReadingsResponse,
  FortuneReadingsStats,
  Paginator,
  AiDashboardResponse,
  AiHero,
  AiProviderSummary,
  AiBotsSummary,
  AiInference,
  AiBot,
  AiBotsResponse,
  WithdrawalRequest,
  WithdrawalsListResponse,
  AnalyticsOverview,
  AdminUserListItem,
  AdminUsersResponse,
  AdminUserStats,
  Iso8601,
} from './types';
export { pairConnection, verifyConnection, loginAndPair, verifyTwoFactorAndPair } from './pair';
export type { PairResult, LoginPairResult, PairUser } from './pair';
export { useAdminData, invalidate, evict, refreshAll } from './useAdminData';
export type { AdminDataResult, DataSource, UseAdminDataOptions } from './useAdminData';
export { useFortuneFeed } from './useFortuneFeed';
export { useReadingDetail } from './useReadingDetail';
export { useUserDetail } from './useUserDetail';
export { getDeviceId, getDeviceName, setDeviceName, resetDeviceIdentity } from './device';
